### ISSUE TITLE
JourneyMap Integration?

### ISSUE THREAD

**Issue by QianFuv** [CCr4ft3r/geotagged-screenshots#1]

**Comment by QianFuv** [comment]
I will change to xaero.

**Comment by CCr4ft3r** [comment]
No answer didn't meant I didn't wanted to implement it ;)
So feel free to reopen this issue any time if you still want compatibility with JourneyMap.

**Comment by QianFuv** [comment]
Thank you for your response. I will reopen this issue at the earliest opportunity when I have this idea in mind.

**Comment by TheDeviantCrafter** [comment]
I would like to see this added as well
