### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by Arborsm** [CCr4ft3r/geotagged-screenshots#2]
imma try to port it to 1.20.1,but the [`blit`](https://github.com/Arborsm/geotagged-screenshots/blob/1.20.1/src/main/java/com/ccr4ft3r/geotaggedscreenshots/util/RenderUtil.java) need `ResourceLocation`, hmm don't know how to make it,and have to sleep XD

![image](https://github.com/CCr4ft3r/geotagged-screenshots/assets/44860537/8dc2fa51-be5e-4c15-ac38-5d2cbbda5031)

**Comment by Arborsm** [comment]
just need it to make everything work, I think.

**Comment by CCr4ft3r** [comment]
Thx for your help :+1: 
ATM I'm not currently familiar with 1.20, so I can't really help.
But feel free to give it a try and don't worry: If it's not working out I'll port it at the latest when it comes out of beta.

**Comment by Arborsm** [comment]
> Thx for your help 👍 ATM I'm not currently familiar with 1.20, so I can't really help. But feel free to give it a try and don't worry: If it's not working out I'll port it at the latest when it comes out of beta.

All done. Could you make a new branch to [it](https://github.com/Arborsm/geotagged-screenshots/tree/1.20.1)? Maybe could optimize it, left to you. I'm not good at programming XD.

**Comment by Arborsm** [comment]
![d7716419745b9697db6a6260806bcde2](https://github.com/CCr4ft3r/geotagged-screenshots/assets/44860537/01998f7c-877a-4280-835f-75a1b9243b89)

**Comment by CCr4ft3r** [comment]
Great👍 I will create a new 1.20 branch based on the 1.19.2 branch. After that you can create a pull request targeting that new 1.20 branch. I will then merge it

**Comment by Arborsm** [comment]
> Great👍 I will create a new 1.20 branch based on the 1.19.2 branch. After that you can create a pull request targeting that new 1.20 branch. I will then merge it

just ping me when you made it ^^

**Comment by CCr4ft3r** [comment]
Done: https://github.com/CCr4ft3r/geotagged-screenshots/tree/1.20.1

**Comment by DoloSaber** [comment]
Is it possible to port to fabric? Because it's really, really, really cool. I so wish I could use it at fabric.

**Comment by DoloSaber** [comment]
Is it possible to port to fabric? Because it's really, really, really cool. I so wish I could use it at fabric.

> 我试着把它移植到 1.20.1 上，但是[](https://github.com/Arborsm/geotagged-screenshots/blob/1.20.1/src/main/java/com/ccr4ft3r/geotaggedscreenshots/util/RenderUtil.java)需要，嗯不知道怎么制作，只好休眠 XD`ResourceLocation`
> 
> ![图像](https://private-user-images.githubusercontent.com/44860537/291386088-8dc2fa51-be5e-4c15-ac38-5d2cbbda5031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjc5OTQsIm5iZiI6MTcyNTAyNzY5NCwicGF0aCI6Ii80NDg2MDUzNy8yOTEzODYwODgtOGRjMmZhNTEtYmU1ZS00YzE1LWFjMzgtNWQyY2JiZGE1MDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDE0MjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNjY0YjNlNzRkMjRiODZiNjFiNTkyMDA3NDZkMGUxMTIxNzNkYjlhOWZmMGE2MjJiNmNiZDczODgzYTU4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wkH_6g8du21nODhJN_ZjyS6GHY26yDwN39XbeWHYJ8M)

Is it possible to port to fabric? Because it's really, really, really cool. I so wish I could use it at fabric.

**Comment by DoloSaber** [comment]
> 我认为，只需要它来让一切正常。

Is it possible to port to fabric? Because it's really, really, really cool. I so wish I could use it at fabric.
