### ISSUE TITLE
Crach 1.20.1

### ISSUE THREAD

**Issue by Quantum-mutnauQ** [CCr4ft3r/geotagged-screenshots#4]
If I join a server(Vanilla) with the mod a change the world and open the map the game crash.
With change world I mean go from the lobby in a game.

Forge: 1.20.1 - 47.2.19
Xaeros MiniMap: 23.9.3
Xaeros WorldMap: 1.37.2 

Log:
[log.txt](https://github.com/CCr4ft3r/geotagged-screenshots/files/13787627/log.txt)

**Comment by CCr4ft3r** [comment]
Geotagged Screenshots is required on client and on server side. Try to add it on the server side too and it should work fine.

**Comment by Quantum-mutnauQ** [comment]
the problem is that the server is a vanilla server like Hypixel. I i join the server and open the map it crash the game

**Comment by CCr4ft3r** [comment]
This mod is required on both sides: server and client. Having it only on client side will not work. It needs to be installed on the server side too. So for your case this is not going to work

**Comment by Quantum-mutnauQ** [comment]
thanks for the quick answer @CCr4ft3r
